"""
build_overview.py
=================

Regenerates the at-a-glance human roster of the flat sector classification, in
two languages from the SAME canonical files:

  SECTORS.md        English
  SECTORS.zh-TW.md  Traditional Chinese (繁體中文)

Two parts each:
  1. Full sector table: every sector, its role (FACTOR/RESIDUAL) + size, and
     the coins it holds (all 232).
  2. Universe tiers: for each TOP-N tier, the sectors it spans and which of
     that tier's coins fall in each.

Pure function of the committed canonical files — no network, no plans/.
    Inputs : classification/sector.csv, classification/sector_roles.json,
             classification/universe_tiers.json
    Outputs: SECTORS.md, SECTORS.zh-TW.md (repo root)

Run:
    python scripts/build_overview.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
SECTOR_CSV     = ROOT / "classification" / "sector.csv"
SECTOR_ROLES   = ROOT / "classification" / "sector_roles.json"
UNIVERSE_TIERS = ROOT / "classification" / "universe_tiers.json"

GLOSS_EN = {
    "smart_contract_platform": "Sovereign general-purpose L1/L2 gas & staking tokens (incl. AI-marketed L1s)",
    "defi":                    "On-chain financial protocols (DEX, lending, perps, LST, RWA, NFT-fi, launchpads)",
    "meme":                    "Attention/community tokens with no holder cash-flow claim",
    "information_technology":  "On-chain service/access/middleware (identity, data-service, access-gating)",
    "metaverse_gaming":        "Games, NFT/IP brands, virtual worlds, fan tokens",
    "eth_scaling":             "Rollups & L2s settling to Ethereum",
    "interoperability":        "Cross-chain messaging, bridges, modular DA, app-chain hubs",
    "oracles_data":            "Verified-data feed & oracle networks",
    "value_transfer":          "Monetary / payment settlement assets (BTC, XRP, LTC…)",
    "compute_storage":         "Decentralized physical-resource DePIN — GPU/compute, storage, bandwidth",
    "captive_franchise":       "Single-operator off-chain revenue tokens (exchange/platform/fund/marketplace)",
    "OTHER":                   "Non-directional residual pool (zombie / near-dead chains)",
    "privacy":                 "Privacy-preserving settlement chains",
}

GLOSS_ZH = {
    "smart_contract_platform": "通用型主權 L1/L2 公鏈,gas/質押(含被當「AI 鏈」行銷、本質仍是 L1 者)",
    "defi":                    "鏈上金融協議(DEX、借貸、永續、流動性質押、RWA、NFT-fi、launchpad)",
    "meme":                    "注意力/社群幣,對持幣者無現金流主張",
    "information_technology":  "鏈上服務/存取/中介(身分、資料服務、access-gating)",
    "metaverse_gaming":        "遊戲、NFT/IP 品牌、虛擬世界、粉絲代幣",
    "eth_scaling":             "結算回 Ethereum 的 Rollup / L2",
    "interoperability":        "跨鏈訊息、橋、模組化 DA、應用鏈樞紐",
    "oracles_data":            "驗證資料餵價 / 預言機網路",
    "value_transfer":          "貨幣 / 支付結算資產(BTC、XRP、LTC…)",
    "compute_storage":         "去中心化實體資源 DePIN——GPU/算力、儲存、頻寬",
    "captive_franchise":       "單一鏈下營運方營收回購型代幣(交易所/平台/基金/市場)",
    "OTHER":                   "非方向性殘差池(殭屍 / 近乎死亡的鏈)",
    "privacy":                 "隱私結算鏈",
}

LANG = {
    "en": {
        "out": "SECTORS.md",
        "title": "# Crypto Sector Classification — Roster",
        "summary": "**{n} coins · {s} sectors** ({f} FACTOR, {r} RESIDUAL) · OKX USDT-margined perpetual universe.",
        "legend": (
            "`FACTOR` = the group shows directional co-movement distinguishable from a "
            "size-matched random null (it survives validation as a real axis). "
            "`RESIDUAL` = an economically coherent label that does **not** clear that bar; "
            "it is named for interpretability but pooled into the market-neutral residual "
            "when group-neutralizing. See `validation/sector_okx/REPORT.md`."
        ),
        "autogen": ("Auto-generated by `scripts/build_overview.py` from "
                    "`classification/sector.csv`. Do not edit by hand."),
        "s1": "## 1 · Sectors → coins (full universe)",
        "th_full": "| Sector | Role | n | Coins |",
        "defs": "**Sector definitions**",
        "s2": "## 2 · Universe tiers → sector breakdown",
        "s2desc": ("Each tier is the top-N coins by market cap within this universe. The table "
                   "shows which sectors the tier spans and which of the tier's coins sit in each "
                   "(coins listed in market-cap rank order)."),
        "tier": "### {label}  ·  {k} coins  ·  {c} / {t} sectors",
        "th_tier": "| Sector | Role | # | Coins |",
        "gloss": GLOSS_EN,
    },
    "zh": {
        "out": "SECTORS.zh-TW.md",
        "title": "# 加密貨幣 Sector 分類 — 名冊",
        "summary": "**{n} 幣 · {s} 個 sector**({f} 個 FACTOR、{r} 個 RESIDUAL)· OKX USDT 本位永續宇宙。",
        "legend": (
            "`FACTOR` = 該組展現可與「同規模隨機 null」區分的方向性同向(通過驗證,是真實的軸)。"
            "`RESIDUAL` = 經濟上連貫、但未達該門檻的標籤;保留作可解讀的名稱,但在 group-neutralize "
            "時併入市場中性殘差池。詳見 `validation/sector_okx/REPORT.md`。"
        ),
        "autogen": ("本檔由 `scripts/build_overview.py` 從 `classification/sector.csv` 自動生成,"
                    "請勿手動編輯。"),
        "s1": "## 1 · Sector → 幣(全宇宙)",
        "th_full": "| Sector | 角色 | n | 幣 |",
        "defs": "**Sector 定義**",
        "s2": "## 2 · 各 TOP universe → sector 拆解",
        "s2desc": ("每個 tier 是此宇宙內市值前 N 名的幣。下表列出該 tier 橫跨哪些 sector,"
                   "以及各 sector 收了該 tier 的哪些幣(幣按市值排序)。"),
        "tier": "### {label}  ·  {k} 幣  ·  {c} / {t} 個 sector",
        "th_tier": "| Sector | 角色 | # | 幣 |",
        "gloss": GLOSS_ZH,
    },
}


def role_badge(role: str) -> str:
    return "🟢 FACTOR" if role == "FACTOR" else "⚪ RESIDUAL"


def render(L, members, roles, ordered, tiers, sym2sector, n_factor, n_resid, total_coins):
    g = L["gloss"]
    out: list[str] = []
    out.append(L["title"])
    out.append("")
    out.append(L["summary"].format(n=total_coins, s=len(members), f=n_factor, r=n_resid))
    out.append("")
    out.append(L["legend"])
    out.append("")
    out.append(L["autogen"])
    out.append("")
    out.append("---")
    out.append("")

    # Part 1 — full sector table
    out.append(L["s1"])
    out.append("")
    out.append(L["th_full"])
    out.append("|---|---|--:|---|")
    for s in ordered:
        coins = ", ".join(members[s])
        out.append(f"| **{s}** | {role_badge(roles[s]['role'])} | {roles[s]['n']} | {coins} |")
    out.append("")
    out.append(L["defs"])
    out.append("")
    for s in ordered:
        out.append(f"- **{s}** — {g.get(s, '')}")
    out.append("")
    out.append("---")
    out.append("")

    # Part 2 — universe tiers
    out.append(L["s2"])
    out.append("")
    out.append(L["s2desc"])
    out.append("")
    disp_rank = {s: i for i, s in enumerate(ordered)}
    for tier in ["top10", "top20", "top30", "top50", "top100"]:
        if tier not in tiers:
            continue
        syms = tiers[tier]
        by_sector: dict[str, list[str]] = {}
        for sym in syms:
            by_sector.setdefault(sym2sector[sym], []).append(sym)
        label = "TOP " + tier.replace("top", "")
        out.append(L["tier"].format(label=label, k=len(syms), c=len(by_sector), t=len(members)))
        out.append("")
        out.append(L["th_tier"])
        out.append("|---|---|--:|---|")
        for s in sorted(by_sector, key=lambda x: (-len(by_sector[x]), disp_rank[x])):
            coins = ", ".join(by_sector[s])
            out.append(f"| **{s}** | {role_badge(roles[s]['role'])} | {len(by_sector[s])} | {coins} |")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    sec = pd.read_csv(SECTOR_CSV, dtype=str, keep_default_na=False)
    roles = json.loads(SECTOR_ROLES.read_text(encoding="utf-8"))
    tiers = json.loads(UNIVERSE_TIERS.read_text(encoding="utf-8"))

    members: dict[str, list[str]] = {}
    for _, r in sec.iterrows():
        members.setdefault(r["sector"], []).append(r["symbol"])
    for s in members:
        members[s] = sorted(members[s])

    total_coins = sum(len(v) for v in members.values())
    assert total_coins == 232, "expected 232 coins"
    assert set(members) == set(roles), "sector.csv labels != sector_roles.json"

    def order_key(s: str):
        r = roles[s]
        return (0 if r["role"] == "FACTOR" else 1, -r["n"], s)

    ordered = sorted(members, key=order_key)
    n_factor = sum(1 for s in members if roles[s]["role"] == "FACTOR")
    n_resid  = len(members) - n_factor
    sym2sector = dict(zip(sec["symbol"], sec["sector"]))

    for lang in ("en", "zh"):
        L = LANG[lang]
        text = render(L, members, roles, ordered, tiers, sym2sector, n_factor, n_resid, total_coins)
        (ROOT / L["out"]).write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {L['out']} — {len(members)} sectors, {total_coins} coins, "
              f"{len([t for t in ['top10','top20','top30','top50','top100'] if t in tiers])} tiers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
