"""
build_overview.py
=================

Regenerates SECTORS.md — the at-a-glance human roster of the flat sector
classification. Two parts:

  1. Full sector table: every sector, its role (FACTOR/RESIDUAL) + size, and
     the coins it holds (all 232).
  2. Universe tiers: for each TOP-N tier, the sectors it spans and which of
     that tier's coins fall in each.

Pure function of the committed canonical files — no network, no plans/.
    Inputs : classification/sector.csv, classification/sector_roles.json,
             classification/universe_tiers.json
    Output : SECTORS.md (repo root)

Run:
    python scripts/build_overview.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
SECTOR_CSV     = ROOT / "classification" / "sector.csv"
SECTOR_ROLES   = ROOT / "classification" / "sector_roles.json"
UNIVERSE_TIERS = ROOT / "classification" / "universe_tiers.json"
OUT            = ROOT / "SECTORS.md"

# Human-friendly one-line gloss per sector (economics-first definition).
GLOSS = {
    "smart_contract_platform": "Sovereign general-purpose L1/L2 gas & staking tokens (incl. AI-marketed L1s)",
    "defi":                    "On-chain financial protocols (DEX, lending, perps, LST, RWA, NFT-fi, launchpads)",
    "meme":                    "Attention/community tokens with no holder cash-flow claim",
    "information_technology":  "On-chain service/access/middleware (identity, data-service, access-gating)",
    "metaverse_gaming":        "Games, NFT/IP brands, virtual worlds, fan tokens",
    "eth_scaling":             "Rollups & L2s settling to Ethereum",
    "interoperability":        "Cross-chain messaging, bridges, modular DA, app-chain hubs",
    "oracles_data":            "Verified-data feed & oracle networks",
    "value_transfer":          "Monetary / payment settlement assets (BTC, XRP, LTC…)",
    "compute_storage":         "Decentralized physical-resource DePIN — GPU/compute, storage, bandwidth",
    "captive_franchise":       "Single-operator off-chain revenue tokens (exchange/platform/fund/marketplace)",
    "OTHER":                   "Non-directional residual pool (zombie / near-dead chains)",
    "privacy":                 "Privacy-preserving settlement chains",
}


def role_badge(role: str) -> str:
    return "🟢 FACTOR" if role == "FACTOR" else "⚪ RESIDUAL"


def main() -> int:
    sec = pd.read_csv(SECTOR_CSV, dtype=str, keep_default_na=False)
    roles = json.loads(SECTOR_ROLES.read_text(encoding="utf-8"))
    tiers = json.loads(UNIVERSE_TIERS.read_text(encoding="utf-8"))

    # sector -> ordered list of tickers (alphabetical, matches CSV order)
    members: dict[str, list[str]] = {}
    for _, r in sec.iterrows():
        members.setdefault(r["sector"], []).append(r["symbol"])
    for s in members:
        members[s] = sorted(members[s])

    assert sum(len(v) for v in members.values()) == 232, "expected 232 coins"
    assert set(members) == set(roles), "sector.csv labels != sector_roles.json"

    # Display order: FACTOR first then RESIDUAL, each by size desc, ties by name.
    def order_key(s: str):
        r = roles[s]
        return (0 if r["role"] == "FACTOR" else 1, -r["n"], s)

    ordered = sorted(members, key=order_key)

    n_factor = sum(1 for s in members if roles[s]["role"] == "FACTOR")
    n_resid  = len(members) - n_factor

    L: list[str] = []
    L.append("# Crypto Sector Classification — Roster")
    L.append("")
    L.append(
        f"**{sum(len(v) for v in members.values())} coins · {len(members)} sectors** "
        f"({n_factor} FACTOR, {n_resid} RESIDUAL) · OKX USDT-margined perpetual universe."
    )
    L.append("")
    L.append(
        "`FACTOR` = the group shows directional co-movement distinguishable from a "
        "size-matched random null (it survives validation as a real axis). "
        "`RESIDUAL` = an economically coherent label that does **not** clear that bar; "
        "it is named for interpretability but pooled into the market-neutral residual "
        "when group-neutralizing. See `validation/sector_okx/REPORT.md`."
    )
    L.append("")
    L.append("Auto-generated by `scripts/build_overview.py` from "
             "`classification/sector.csv`. Do not edit by hand.")
    L.append("")
    L.append("---")
    L.append("")

    # ------------------------------------------------------------------
    # Part 1 — full sector table
    # ------------------------------------------------------------------
    L.append("## 1 · Sectors → coins (full universe)")
    L.append("")
    L.append("| Sector | Role | n | Coins |")
    L.append("|---|---|--:|---|")
    for s in ordered:
        coins = ", ".join(members[s])
        L.append(f"| **{s}** | {role_badge(roles[s]['role'])} | {roles[s]['n']} | {coins} |")
    L.append("")
    L.append("**Sector definitions**")
    L.append("")
    for s in ordered:
        L.append(f"- **{s}** — {GLOSS.get(s, '')}")
    L.append("")
    L.append("---")
    L.append("")

    # ------------------------------------------------------------------
    # Part 2 — universe tiers
    # ------------------------------------------------------------------
    L.append("## 2 · Universe tiers → sector breakdown")
    L.append("")
    L.append(
        "Each tier is the top-N coins by market cap within this universe. The table "
        "shows which sectors the tier spans and which of the tier's coins sit in each "
        "(coins listed in market-cap rank order)."
    )
    L.append("")

    sym2sector = dict(zip(sec["symbol"], sec["sector"]))

    tier_order = ["top10", "top20", "top30", "top50", "top100"]
    for tier in tier_order:
        if tier not in tiers:
            continue
        syms = tiers[tier]
        # group preserving rank order
        by_sector: dict[str, list[str]] = {}
        for sym in syms:
            by_sector.setdefault(sym2sector[sym], []).append(sym)
        n_cov = len(by_sector)
        label = "TOP " + tier.replace("top", "")
        L.append(f"### {label}  ·  {len(syms)} coins  ·  {n_cov} / {len(members)} sectors")
        L.append("")
        L.append("| Sector | Role | # | Coins |")
        L.append("|---|---|--:|---|")
        # order sectors by member count desc, ties by display order
        disp_rank = {s: i for i, s in enumerate(ordered)}
        for s in sorted(by_sector, key=lambda x: (-len(by_sector[x]), disp_rank[x])):
            coins = ", ".join(by_sector[s])
            L.append(f"| **{s}** | {role_badge(roles[s]['role'])} | {len(by_sector[s])} | {coins} |")
        L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(members)} sectors, "
          f"{sum(len(v) for v in members.values())} coins, "
          f"{len([t for t in tier_order if t in tiers])} tiers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
